---
title: "R02_2 Pivot analysis on tp theft with dplyr"
author: "Jilung Hsieh"
date: "2019/9/2"
output:
  html_document:
    theme: cerulean
    highlight: zenburn
    toc: yes
    toc_float:
      collapsed: no
    df_print: paged
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# loading packages
```{r}
library(tidyverse)
options(stringsAsFactors = F)
```

# Reading data
```{r}
library(httr)
url <- "http://data.taipei/opendata/datalist/datasetMeta/download?id=68785231-d6c5-47a1-b001-77eec70bec02&rid=34a4a431-f04d-474a-8e72-8d3f586db3df"
df_base<- read.csv(url, fileEncoding = "big5")

```

```{r}
# Read by read_csv()
# Will raise error
# Error in make.names(x) : invalid multibyte string at '<bd>s<b8><b9>'
# df <- read_csv("data/tp_theft.csv")

# read_csv() with locale encoding = "Big5"
df <- read_csv("data/tptheft.csv", locale = locale(encoding = "Big5"))
```


# Cleaning data I
- Renaming variables by `select()`
- Generating variable year
- Generating variable month
- Retrieving area
```{r}
df <- read_csv("data/tptheft.csv", locale = locale(encoding = "Big5")) %>% 
    select(id = 編號, 
           cat = 案類, 
           date = `發生(現)日期`, 
           time = `發生時段`, 
           location = `發生(現)地點`) %>%
    mutate(year = date %/% 10000) %>%
    mutate(month = date %/% 100 %% 100) %>%
    mutate(area = stringr::str_sub(location, 4, 6)) %>%
    mutate(county = stringr::str_sub(location, 1, 3))
```
```{r}
library(httr)
url <- "http://data.taipei/opendata/datalist/datasetMeta/download?id=68785231-d6c5-47a1-b001-77eec70bec02&rid=34a4a431-f04d-474a-8e72-8d3f586db3df"
df <- read.csv(url, fileEncoding = "big5")
df <- df%>%
    select(date = `發生.現.日期`, 
           time = `發生時段`, 
           location = `發生.現.地點`) %>%
    mutate(year = date %/% 10000,
           month = date %/% 100 %% 100,
           area = stringr::str_sub(location, 4, 6),
           county = stringr::str_sub(location, 1, 3),
           time = str_sub(time, 1, 2)) %>%
    filter(county=='台北市')

```

# Cleaning data II
- Filtering out irrelevant data records

```{r}
# readr::guess_encoding("data/tp_theft.csv")
df <- df %>%
    # count(year) %>% View
    filter(year >= 104) %>%
    # count(time) %>% View
    filter(!time %in% c("00~02", "02~04", "06~08", "08~10", "12~14", "14~16", "18~20", "20~22")) %>%
    # count(location) %>%
    filter(!area %in% c("中和市", "板橋市"))
```


# Long to wide form
- `count()` two variables
- `spread()` spread one variable as columns to wide form

```{r}
# count() then spread()
df.wide <- df %>% 
    count(area, time) %>%
    spread(time, n, fill=0) 
```


# Setting time as row.name for mosaicplot
```{r}
df.wide <- data.frame(df.wide)
row.names(df.wide) <- df.wide$area
df.wide$area <- NULL
```




```{r warning=FALSE}

# Specify fonts for Chinese
# par(family=('STKaiti')) 
par(family=('Heiti TC Light')) # for mac

# Specify colors
colors <- c('#D0104C', '#DB4D6D', '#E83015',  '#F75C2F',
            '#E79460', '#E98B2A', '#9B6E23', '#F7C242',
            '#BEC23F', '#90B44B', '#66BAB7', '#1E88A8')

# mosaicplot()
mosaicplot(df.wide, color=colors, border=0, off = 3,
           main="Theft rate of Taipei city (region by hour)")

```
